@isTest
public with sharing class SoqlAggregateTest {
    /*
    @isTest
    public static void TestCloseOpportunityData()
    {
        TestDataFactory.createCloseWonOpportunity(5);
        
        System.startTest();
        SoqlAggregate soqlAggregateObject = new SoqlAggregate();
        soqlAggregateObject.closeOpportunityData();
        System.stopTest();
        System.assertEquals(500,soqlAggregateObject);
    }
    */

    
}
