@isTest
public class TestDataFactory 
{
    /*
    
    @isTest
    public static List<Opportunity> createCloseWonOpportunity(Integer numOpportunities)
    {
        List<Opportunity> opportunities = new List<Opportunity>();
    
            for(Integer i=0;i<numOpportunities;i++) 
        {
            Opportunity opportunityInstance = new Opportunity(Name='TestAccount' + i ,StageName = 'Closed Won',
                                                                                    closeDate = THIS_FISCAL_YEAR,Amount =100);
            opportunities.add(opportunityInstance);
        }
        insert opportunities;
        return opportunities;
    }
    */


}
